Repository two-shots-later/vitruvian-vtt, pull requests merged in 2024-09, with the labels that each got.

#27 Ingest Ancestry and Improve Ingestion Code
  src-tauri/src/ingestion/core/description.rs
  src-tauri/src/ingestion/core/mod.rs
  src-tauri/src/ingestion/core/publication.rs
  src-tauri/src/ingestion/core/traits.rs
  src-tauri/src/ingestion/mod.rs
  src-tauri/src/ingestion/pf2e/ancestry/boost.rs
  src-tauri/src/ingestion/pf2e/ancestry/flaw.rs
  src-tauri/src/ingestion/pf2e/ancestry/mod.rs
  src-tauri/src/ingestion/pf2e/classes/hit_points.rs
  src-tauri/src/ingestion/pf2e/classes/mod.rs
  src-tauri/src/ingestion/pf2e/core/item.rs
  src-tauri/src/ingestion/pf2e/core/languages.rs
  src-tauri/src/ingestion/pf2e/core/mod.rs
  src-tauri/src/ingestion/pf2e/core/rarity.rs
  src-tauri/src/ingestion/pf2e/core/rule.rs
  src-tauri/src/ingestion/pf2e/core/size.rs
  src-tauri/src/ingestion/pf2e/core/traits.rs
  src-tauri/src/ingestion/pf2e/core/vision.rs
  src-tauri/src/ingestion/pf2e/mod.rs
Labels: enhancement, backend

#25 Adding Entities, Components for Backend
  src-tauri/.gitignore
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/build.rs
  src-tauri/src/ecs/mod.rs
  src-tauri/src/lib.rs
  src-types/.gitignore
  src-types/Cargo.lock
  src-types/Cargo.toml
  src-types/src/component/core.rs
  src-types/src/component/mod.rs
  src-types/src/entity.rs
  src-types/src/lib.rs
  src/App.tsx
  src/types/Entity.ts
  src/types/gen/Bulk.ts
Labels: enhancement, frontend, backend

#28 Adding Support for Sending Data Between the Frontend and the Backend
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/build.rs
  src-tauri/src/ecs/mod.rs
  src-tauri/src/lib.rs
  src-types/Cargo.lock
  src-types/Cargo.toml
  src-types/src/component/core.rs
  src-types/src/component/mod.rs
  src-types/src/entity.rs
  src-types/src/lib.rs
  src/App.tsx
  src/main.tsx
  src/types/Entity.ts
  src/types/gen/Component.ts
  src/types/gen/Damage.ts
  src/types/gen/Dice.ts
  src/types/gen/Entity.ts
  src/types/gen/Name.ts
Labels: enhancement, frontend, backend

#31 Adding Frontend Support for Themes
  .DS_Store
  index.html
  package-lock.json
  package.json
  postcss.config.js
  src-tauri/src/commands/mod.rs
  src-tauri/src/commands/themes.rs
  src-tauri/src/lib.rs
  src-tauri/tauri.conf.json
  src-types/src/lib.rs
  src-types/src/theme.rs
  src/.DS_Store
  src/App.css
  src/App.tsx
  src/common/theme.ts
  src/main.tsx
  src/routes/ComponentLibrary/ComponentLibrary.tsx
  src/routes/Home/Home.tsx
  src/routes/routes.ts
  src/types/gen/VitruvianTheme.ts
  tailwind.config.js
Labels: enhancement, frontend

#32 Add the Icon and Badge Components
  .gitignore
  package-lock.json
  package.json
  src/.DS_Store
  src/assets/.DS_Store
  src/assets/CrimsonPro-Italic-VariableFont_wght.ttf
  src/assets/CrimsonPro-VariableFont_wght.ttf
  src/assets/spirtes.svg
  src/components/Badge.tsx
  src/components/Icon.tsx
  src/routes/Home/Home.tsx
  src/types/Icon.ts
  src/types/gen/.DS_Store
  src/types/gen/VitruvianTheme.ts
  tailwind.config.js
Labels: enhancement, frontend
